#!/usr/bin/env zsh
set -euo pipefail

SCRIPT_PATH=${0/#[!\/]/"$PWD/${0:0:1}"}
SCRIPT_DIR=${SCRIPT_PATH%/*}

SAVEPATH="tests"
IMPORTS="import"
INFILE=mal-completed-presorted.csv
COMPARISONS=comparisons.feather
# INFILE=test-presorted.csv
OUTFILE=test-$(date -u +"%Y%m%dT%H%M").csv

ask() {
    local prompt default reply
    if [[ ${2:-} = 'Y' ]]; then
        prompt='Y/n'
        default='Y'
    elif [[ ${2:-} = 'N' ]]; then
        prompt='y/N'
        default='N'
    else
        prompt='y/n'
        default=''
    fi
    while true; do
        # Ask the question (not using "read -p" as it uses stderr not stdout)
        echo -n "$1 [$prompt] "
        # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
        read -r reply </dev/tty
        # Default?
        if [[ -z $reply ]]; then
            reply=$default
        fi
        # Check if the reply is valid
        case "$reply" in
            Y* | y*) return 0 ;;
            N* | n*) return 1 ;;
        esac
    done
}
cp -a "${COMPARISONS}" "${COMPARISONS}-$(date -u +"%Y%m%dT%H%M%S)"

awk -F ',' -v FPAT="([^,]+)|(\"[^\"]+\")" -v OFS=', ' '{gsub(/"/,"",$2); print $1,$2,$3,$4,$5}' "${SAVEPATH}/${IMPORTS}/${INFILE}" > "${SAVEPATH}/${INFILE}"

# Rscript "${SCRIPT_DIR}/resorter.R" -i "${INFILE}" --quantiles '0 0.5 0.75 0.89 0.93 0.95 0.96 0.97 0.98 0.99 0.995' -o "$OUTFILE" --progress --header --colorize --working-directory "$SAVEPATH" --comparisons "${IMPORTS}/${COMPARISONS}"

Rscript "${SCRIPT_DIR}/resorter.R" -i "${INFILE}" --levels 10 -o "$OUTFILE" --progress --header --colorize --working-directory "$SAVEPATH" --comparisons "models/${COMPARISONS}"

# Rscript resorter.R -i "$INFILE" --quantiles '0 0.05 0.1 0.2 0.3 0.4 0.5 0.97 0.98 0.99 0.995' -o "$OUTFILE" --progress

# Rscript resorter.R -i =(awk -F ',' -v FPAT="([^,]+)|(\"[^\"]+\")" -v OFS=', ' '{gsub(/"/,"",$2); print $1,$2}' test-20210926T0511.csv) --quantiles '0 0.05 0.1 0.2 0.3 0.4 0.5 0.97 0.98 0.99 0.995' -o "$OUTFILE" --progress

pushd "$SAVEPATH"
ask "Keep result?" || rm "$OUTFILE"
# rm "$OUTFILE"
trap popd EXIT
